install:
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report

language: java
jdk:
- oraclejdk8

notifications:
  email:
  - enric.ballo@bluecodex.com